Order history
CSCE331-Fall2024/project-3-team-5b pull request #14
Opened 2024-11-24 20:58 UTC by bbriannab

2024-11-25 00:29 UTC, Daniel-Lam1702 requested changes

2024-11-25 00:29 UTC, Daniel-Lam1702 commented on Backend/index.js
Consider returning more information of the orders such as menu items, price, and item components.

2024-11-25 00:29 UTC, Daniel-Lam1702 commented on Front-End/src/pages/MenuBoard.css
Is there any need to make changes to the menu board for the order history?

2024-11-25 04:26 UTC, bbriannab commented on Front-End/src/pages/MenuBoard.css
I wanted to reformat the menu board to left-align the text for each menu item.

2024-11-25 04:29 UTC, Daniel-Lam1702 commented on Front-End/src/pages/MenuBoard.css
Got it, for more organization even if it is a small change, it is better to make a separate branch for this.

2024-12-10 02:11 UTC, Xach-A approved these changes
looks good

2024-12-10 02:13 UTC, Daniel-Lam1702 approved these changes

2024-12-10 02:13 UTC, merged