added documentation to current code
CSCE331-Fall2024/project-3-team-5b pull request #26
Opened 2024-12-08 20:03 UTC by aidanthomas26

2024-12-08 20:40 UTC, Daniel-Lam1702 requested changes
@aidanthomas26, looks good to me but please address my comments and request a second review.

2024-12-08 20:40 UTC, Daniel-Lam1702 commented on Front-End/src/pages/Cashier/CashierNavbar.jsx
The CashierNavbar.jsx got replaced by the CashierOrderPage.jsx

2024-12-08 20:40 UTC, Daniel-Lam1702 commented on Front-End/src/pages/Manager/InventoryManager.jsx
Please confirm with @Xach-A  the completeness of this file since we merged his changes.

2024-12-08 21:04 UTC, Xach-A commented on Front-End/src/pages/Manager/InventoryManager.jsx
I resolved the changes. This part is good now.

2024-12-08 22:38 UTC, Daniel-Lam1702 requested changes
Only need to fix the CashierNavbar.jsx.

2024-12-09 01:33 UTC, Daniel-Lam1702 approved these changes
Looks good to me.

2024-12-09 01:33 UTC, merged